name: skeleton_project
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider:
  get_it:
  intl:
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter
  


flutter:

  uses-material-design: true
